# Generated by Django 5.2.3 on 2025-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('parent_ids', models.JSONField(blank=True, default=list)),
                ('spouse_ids', models.JSONField(blank=True, default=list)),
                ('children_ids', models.JSONField(blank=True, default=list)),
                ('family_id', models.CharField(max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
