# Generated by Django 5.2.3 on 2025-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=24)),
                ('result', models.IntegerField(default=0)),
                ('checks', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'basic_checks',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
