# Generated by Django 4.2.10 on 2025-06-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_basicchecks_person_middle_name_person_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicChecks',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
